### ISSUE TITLE
Bug: git phlow issues --mine lists all issues in repo

### ISSUE THREAD

**Issue by JKrag** [code-cafes/git-phlow#267]
On my version 3.1.0, running
`git phlow issues --mine` lists all issues, not just those assigned to me.

**Comment by groenborg** [comment]
That feature got accidentally butchered during the remake of the command with support for Jira. I am not sure we will bring back `--mine` but instead replace it with a filter function so you have higher customizability of your issue search queries

**Comment by groenborg** [comment]
Stale issue
