### ISSUE TITLE
Create a test suite to run before release for most valuable workflows and systems

### ISSUE THREAD

**Issue by buep** [code-cafes/git-phlow#276]
We should extend testst to include more Windows and Jira testings, so they become part of our smoke test suite somehow.

**Comment by groenborg** [comment]
I think that `bats` would be a nice tool for us to use in this scenario. This way we can create acceptance tests for each command to verify its behaviour

**Comment by groenborg** [comment]
Lets start simple with this one and try it out in a single complex command and a few simple ones to see how it fares. If we achieve the results we want we can expand the test suite to include all our commands. 

Auth however does require a running instance of Jira and Github to work so we probably need to do some mocking or integration / end 2 end tests here in stead

**Comment by buep** [comment]
Okay, I'm fine with trying bats for this.

If case tests are OS specific, we should start writing them for Windows as we're many Linux/MAC users already.

I believe work on also requires a tasks system as well.

I would like this to be part of the testing also.

**Comment by groenborg** [comment]
I do not know is bats are available on windows, but if it's not, I still think it is okay only to conduct the tests on Linux until we have another framework for windows. Workon does require a task system, but we already have a test repository with issue on Github, we can use that and include its usage in the test documentation.

**Comment by buep** [comment]
Okay, back to my requirements - I would like a smoke test that checks the most valuable workflows for me before we release. Currently for me this means:

* runs on Windows in one of the three shells supported
* uses a running jira instance for those commands that usually interacts with task management systems 


We can call is something else than a smoketest, because smoketest usually runs fast. But the above test I would like automated and executed successfully before each and every release.

**Comment by groenborg** [comment]
I can't see no easy way around this. We need to figure out to do headless testing cmd prompt and git bash on windows then.. and also spin up a lira instance. The lira part should be okay, but the windows part is complicated. 

Also if you want a smoke test that runs our workflow windows should not be needed! golang and git performs the same way on the different platforms so there is no reason to test the platform which is what we are doing here.. The only place where it makes sense is when we are working with `auth` and ssh-keys with passwords

**Comment by groenborg** [comment]
If bats however is available on both platforms we can create a script we can run on each of the different shells to verify that they work, which we will execute manually
