### ISSUE TITLE
feature: git phlow home

### ISSUE THREAD

**Issue by groenborg** [code-cafes/git-phlow#284]
As a user I want to go back to my integration branch and have it updated
so I can see any incoming changes locally

git phlow home will checkout the integration, fetch and `pull --rebase` the latest changes. This is a quick way to go see what have been
integrated into the master branch on github and make them available locally.

The command can alternative also be a flag for other commands like `deliver`.
So a `git phlow deliver --home` will switch you back to the integration branch and get the latest updates if any.

Idea groomed together with @JKrag

**Comment by buep** [comment]
Thanks, we can consider that later.

I don't see need to rebase, as the integration branch isn't changed locally and shouldn't be.

**Comment by groenborg** [comment]
The rebase is a must.. if you do a workon, then do another workon and deliver that. The previous workon will be behind and needs to be rebased or merged.

**Comment by groenborg** [comment]
Stale issue
