### ISSUE TITLE
Transfer ownership to code-cafes

### ISSUE THREAD

**Issue by lakruzz** [code-cafes/git-phlow#316]
## Problem
This repo is currently owned by the Praqma organization, but _almost_ all contributions to the repo have been done by people who now are outside the praqma organization.

We're a bunch of people who still use it and would like to maintain it, but it's impractical that we don't have contributing access to the repo.

## Solution
We would like Praqma (@JKrag @meekrosoft @praqma-thi) to transfer the ownership of this repo to @code-cafes (pls add it to the team git-phlow). The main developer on the repo @groenborg is already a member of this organization - and you are all welcome to join.

## Value
The people who care for the code - benevolent dictators, trusted lieutenants get to access to maintain the code, the advantage of a transfer (over a fork) is that all the issues that are in the repo currently will be transferred too - and the new maintainers need them.

**We have a CoDe Café (hackathon) coming up on Friday (this week) so it would be convenient if you could expedite the transfer immediately.**

**Comment by JKrag** [comment]
@lakruzz I will look into this sometime tomorrow.

**Comment by JKrag** [comment]
Transfer completed :-)
@lakruzz Will you add a comment to the readme to remind contributors to change their git remote URL?

**Comment by lakruzz** [comment]
Thank you @JKrag everything went smooth - we're once again hacking the Git Phlow - hope to see you on one of our upcoming cafés.

Regarding the redirect/update of remote settings, it's actually not even necessary.

GitHub has automatically setup a the correct redirects and aliases for https://github.com/praqma/git-phlow (including the SSH protocol) so all current clones are still working exactly as expected.

Thanks again!
